{
 "title": "Database Exporter (PostgreSQL)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "database",
    "label": "Database",
    "query": {
     "query": "label_values(pg_database_size_bytes,datname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Role priveleges count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_users_privileges_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Database Size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=~\"$database\", job=\"postgres-exporter\"} / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Database Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=~\"$database\", state=\"active\", job=\"postgres-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Locks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "pg_locks_count{job=\"postgres-exporter\",datname=~\"$database\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of rows",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_user_tables_n_live_tup{datname=~\"$database\", job=\"postgres-exporter\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of tables",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pg_stat_user_tables_n_live_tup{datname=\"techno_events\", job=\"postgres-exporter\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estimated Active Users",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (usename) (pg_stat_activity_count))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Buffer Cache Hit Ratio %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  rate(pg_stat_database_blks_hit{datname=~\"$database\",job=\"postgres-exporter\"}[5m]) / \r\n  (rate(pg_stat_database_blks_hit{datname=~\"$database\",job=\"postgres-exporter\"}[5m]) + rate(pg_stat_database_blks_read{datname=~\"$database\", job=\"postgres-exporter\"}[5m]))\r\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QPS — transactions/sec (commits + rollbacks, 5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=~\"$database\",job=\"postgres-exporter\"}[5m]) + rate(pg_stat_database_xact_rollback{datname=~\"$database\", job=\"postgres-exporter\"}[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write operations rate (tuples inserted/sec, 1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_inserted{datname=~\"$database\", job=\"postgres-exporter\"}[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read operations rate (blocks read/sec, 1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_blks_read{datname=~\"$database\", job=\"postgres-exporter\"}[1m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}