{
 "title": "Node Exporter (System Metrics)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Server Instance",
    "query": {
     "query": "label_values(node_cpu_seconds_total,instance)"
    }
   },
   {
    "name": "device",
    "label": "Network device",
    "query": {
     "query": "label_values(node_network_receive_bytes_total,device)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Network Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_network_receive_errs_total{device=~\"$device\",instance=\"$instance\"}[5m])\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(node_network_transmit_errs_total{device=~\"$device\",instance=\"$instance\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Traffic по выбранным интерфейсам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=~\"$device\",instance=\"$instance\"}[5m]) * 8 / 1000000",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device=~\"$device\",instance=\"$instance\"}[5m]) * 8 / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Battery Capacity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_power_supply_capacity{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Distribution(Free, Cached, Used)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$instance\"} / 1073741824",
     "legendFormat": "__auto"
    },
    {
     "expr": "(node_memory_Cached_bytes + node_memory_Buffers_bytes{instance=\"node-exporter:9100\"}) / 1073741824",
     "legendFormat": "__auto"
    },
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes{instance=\"node-exporter:9100\"}) / 1073741824",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Uptime (Days)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - node_boot_time_seconds{instance=\"$instance\"}) / 86400",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Heatmap: per-process CPU distribution or IO wait distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(node_pressure_io_waiting_seconds_total{instance=\"$instance\"}[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of running processes",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "node_procs_running{instance=\"$instance\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network traffic — incoming/outgoing (Mbit/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "(sum(rate(node_network_receive_bytes_total{instance=\"node-exporter:9100\"}[5m])) by (instance) * 8) / 1024 / 1024\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum(rate(node_network_transmit_bytes_total{instance=\"node-exporter:9100\"}[5m])) by (instance) * 8) / 1024 / 1024\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk I/O read (bytes/sec) — 5m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{instance=\"node-exporter:9100\"}[5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free disk space (GB) per Device",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device=~\"/dev/.*\",instance=~\"$instance\",job=\"node-exporter\"} / 1073741824",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM usage (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes{instance=\"node-exporter:9100\"})\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total, available, and used memory (in GB)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"} / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$instance\"} / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes{instance=~\"$instance\"}) / 1024 / 1024 / 1024\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load average (1, 5, 15 min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_load5{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_load15{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Использование CPU (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - sum(rate(node_cpu_seconds_total{mode=\"idle\",instance=~\"$instance\"}[5m])) / sum(rate(node_cpu_seconds_total[5m])))\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}